name: lehttp_overrides
description: A Flutter package to resolve Let's Encrypt SSL certificate problems with Android 7.1.1 and below
repository: https://github.com/salamaEnigma/lehttp_overrides_updated.git
homepage: https://github.com/salamaEnigma
version: 1.0.3

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.0.3

dev_dependencies:
  flutter_lints: ^1.0.0
